export enum ApplicationErrorCode {
  // Not Found
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MOVIE_NOT_FOUND = 'MOVIE_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',

  // Conflict
  SESSION_CONFLICT = 'SESSION_CONFLICT',
  SESSION_SOLD_OUT = 'SESSION_SOLD_OUT',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  ROOM_NUMBER_EXISTS = 'ROOM_NUMBER_EXISTS',

  // Forbidden
  USER_UNDERAGE = 'USER_UNDERAGE',
  TICKET_NOT_OWNED = 'TICKET_NOT_OWNED',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // Bad Request
  SESSION_IN_PAST = 'SESSION_IN_PAST',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Unauthorized
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
}
