export enum DomainErrorCode {
  // Validation - Required Fields
  MOVIE_TITLE_REQUIRED = 'MOVIE_TITLE_REQUIRED',
  MOVIE_ID_REQUIRED = 'MOVIE_ID_REQUIRED',
  ROOM_ID_REQUIRED = 'ROOM_ID_REQUIRED',
  USER_ID_REQUIRED = 'USER_ID_REQUIRED',
  SESSION_ID_REQUIRED = 'SESSION_ID_REQUIRED',
  SESSION_DATE_REQUIRED = 'SESSION_DATE_REQUIRED',

  // Validation - Format
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
  INVALID_TIME_SLOT = 'INVALID_TIME_SLOT',

  // Validation - Range
  INVALID_AGE = 'INVALID_AGE',
  INVALID_AGE_RESTRICTION = 'INVALID_AGE_RESTRICTION',
  INVALID_ROOM_NUMBER = 'INVALID_ROOM_NUMBER',
  INVALID_ROOM_CAPACITY = 'INVALID_ROOM_CAPACITY',

  // Business Rules
  SESSION_IN_PAST = 'SESSION_IN_PAST',
}
